entity detection and generic responses extensions
deepmipt/dialog_flow_sdk pull request #1
Opened 2021-10-26 06:53 UTC by dmitrijeuseew

Entity detection - 4Gb RAM, Entity linking - 11 Gb RAM, wiki parser - около 50 Mb RAM

2021-10-28 06:58 UTC, kudep requested changes
- [ ] дим, мы не используем dev.yml , посмотри как оформлен docker-compose.yml надо будет сдеать так же не добавляя ничего лишнего https://github.com/deepmipt/dd_idde_sdk/commit/1f157400537730f429cf1f064e40e12b39ebea5b 
- [ ] Dockerfile не используется, давай тогда его удалим ?
- [ ] много кода просто копипастой из dream sdk должен быть минималистичным и показательным, ксе лишнее надо убрать https://github.com/deepmipt/dd_idde_sdk/blob/098d4d8404cfa8c8c9a507c6831042a839646b95/examples/utils.py#L8-L116 это касается всего PR

2021-10-28 07:37 UTC, danielkornev commented on examples/example_1_basics.py
> +                          ("generic_responses_flow", "generic_response"): generic_response_condition},
good

2021-10-28 07:37 UTC, danielkornev commented on examples/example_1_basics.py
> +            TRANSITIONS: {"node4": has_entities("PERSON")},
looks lovely!

2021-10-28 07:37 UTC, danielkornev commented on examples/example_1_basics.py
> +            RESPONSE: "I also like [singer] songs.",
awesome

2021-10-28 07:39 UTC, danielkornev commented on examples/example_1_basics.py
> +                          ("generic_responses_flow", "generic_response"): generic_response_condition},
maybe write like this:
gr_cnd? (inline with everything else?)

2021-11-03 07:55 UTC, kudep requested changes
- [ ] https://github.com/deepmipt/dd-idde-sdk/blob/9380332b63a8b147f996f3ec9fb6073f1f904b15/examples/utils/utils.py#L24-L25 не определены
- [ ] https://github.com/deepmipt/dd-idde-sdk/blob/9380332b63a8b147f996f3ec9fb6073f1f904b15/examples/utils/utils.py#L47 не определен deepcopy
- [ ] дим, напиши еще пжлст, для каждого сервиса потребляемые ресурсы по RAM

2021-11-06 16:49 UTC, merged